data_folder = "/data/wapor_test"
start_date = "2018-04-20"
end_date = "2018-04-23"
latitude_extent = [33.0, 36.0]
longitude_extent = [35.0, 38.0]
username_earthdata = "lafa"
password_earthdata = "Lf562010"
username_vito = "laustfaerch"
password_vito = "Lf562010"
landcover = "GlobCover"
prepare_level1_data = true
run_level1_ETLook = true
prepare_level2_data = false
run_level2_ETLook = false