data_folder = "/data/wapor_test"
start_date = "2018-04-20"
end_date = "2018-04-25"
latitude_extent = [33.0, 36.0]
longitude_extent = [35.0, 38.0]
username_earthdata = ""
password_earthdata = ""
username_vito = ""
password_vito = ""
landcover = "GlobCover"
prepare_level1_data = true
run_level1_ETLook = true
prepare_level2_data = false
run_level2_ETLook = false